### ISSUE TITLE
Community ToDo

### ISSUE THREAD

**Issue by mchorse** [mchorse/aperture#16]
- [ ] Outside mode improvements:
    - [ ] Add a config option to hide GUIs (i.e. cancel `drawScreen()`) suggested by Agirres
    - [ ] Add a config option to hide HUD overlays (i.e. pumpkin, water, fire, etc.) suggested by Agirres
- [ ] Add a feature to automatically create smooth keyframe handles for bezier
- [ ] Investigate handheld camera technique
- [ ] Add a profile fixture (suggested by Agirres)
- [ ] Agirres also said something about fixture locking...

**Comment by mchorse** [comment]
All of these suggested are pretty outdated... I don't think there is any way for me to implement them.
